# Generated by Django 2.1.1 on 2018-09-15 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180915_0409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='creado',
            new_name='date',
        ),
    ]
