# Generated by Django 2.1.1 on 2018-09-15 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(blank=True, max_length=75)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True, max_length=5000)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='description',
        ),
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.MessageDescription'),
            preserve_default=False,
        ),
    ]
