# Generated by Django 2.1.1 on 2018-09-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180915_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='datauser',
            name='last_progress',
            field=models.IntegerField(default=10),
        ),
    ]
