# Generated by Django 2.1.1 on 2018-09-15 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_datauser_last_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datauser',
            old_name='last_progress',
            new_name='next_progress',
        ),
    ]
