# Generated by Django 2.1.1 on 2018-09-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180915_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='next_progress',
            field=models.IntegerField(default=40),
        ),
    ]
