# Generated by Django 2.1.1 on 2018-09-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180915_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type_transaction',
            field=models.CharField(choices=[('DP', 'Deposit'), ('WD', 'Withdrawal'), ('PM', 'Payment'), ('TR', 'Transference'), ('IV', 'Invest'), ('LD', 'Long-Term Desposit'), ('LO', 'Loan')], max_length=2),
        ),
    ]
